services:
  api:
    build: .
    container_name: parking-api-app
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - mqtt
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: parking-mongodb
    ports:
      - "27017:27017"
    volumes:
      - parking-db-data:/data/db
    restart: unless-stopped

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

volumes:
  parking-db-data: